[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm install --engine-strict false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx serve -s dist/employee-app/browser -l $PORT"